config/routes.rb
MySandwiches::Application.routes.draw do
  resources :newsletters

  devise_for :users
  resources :order_pages
  resources :admin 
   match '/order_list' => 'admin#order', :as => :order_list, via: :get
    match '/about_us' => 'home#about_us', :as => :about_us, via: :get
  
  resources :home

   root 'home#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.role_id == 1
      can :manage, :all    
    elsif user.role_id == 2      
      can :create, OrderPage
      can :read, OrderPage
      can :show, OrderPage
      can :edit, OrderPage    
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bread_type.rb
class BreadType < ActiveRecord::Base
  has_many :order_pages, dependent: :destroy
  attr_accessible :name, :price
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :order_pages
  has_many :users, through: :order_pages, dependent: :destroy
  attr_accessible :comment
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :email
end

app/models/order_page.rb
class OrderPage < ActiveRecord::Base
belongs_to :pickuptime
belongs_to :bread_type
belongs_to :spread
belongs_to :vegetable
belongs_to :sauce
belongs_to :user
attr_accessible :pickuptime_id, :order_quantity, :bread_type_id, :sandwich_type, :spread_id, :spread_ids, :vegetable_id, :vegetable_ids, :sauce_id, :sauce_ids, :user_id, :comment
 
has_and_belongs_to_many :vegetables
has_and_belongs_to_many :spreads
has_and_belongs_to_many :sauces
end

app/models/order_pages_sauces.rb
class OrderPagesSauces < ActiveRecord::Base
  belongs_to :order_page
  belongs_to :sauce
end

app/models/order_pages_spreads.rb
class OrderPagesSpreads < ActiveRecord::Base
  belongs_to :order_page
  belongs_to :spread
end

app/models/order_pages_vegetables.rb
class OrderPagesVegetables < ActiveRecord::Base
  belongs_to :order_page
  belongs_to :vegetable
end

app/models/pickuptime.rb
class Pickuptime < ActiveRecord::Base
  has_many :order_pages, dependent: :destroy
  attr_accessible :pickuptime
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_many :users, dependent: :destroy
end

app/models/sauce.rb
class Sauce < ActiveRecord::Base
  has_many :order_pages, dependent: :destroy
  attr_accessible :name, :price
  
    has_and_belongs_to_many :order_pages
end

app/models/spread.rb
class Spread < ActiveRecord::Base
  has_many :order_pages, dependent: :destroy
  attr_accessible :name, :price
  
  has_and_belongs_to_many :order_pages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :role         
  attr_accessible :email, :password, :password_confirmation, :role_id
  has_many :order_pages
  has_many :comments, through: :order_pages, dependent: :destroy
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
  has_many :order_pages, dependent: :destroy
  attr_accessible :name, :price
  
  has_and_belongs_to_many :order_pages
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController 
  def order
     @order_pages = OrderPage.all     
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
   # before_action :authenticate_user!, except: [:index, :about_us]
   def index
     @order_pages = OrderPage.all
     @order_page = OrderPage.new
   end
   def about_us
     
   end
   
end

app/controllers/order_pages_controller.rb
class OrderPagesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_order_page, only: [:show, :edit, :update, :destroy]
  # caches_page :index

  # GET /order_pages
  # GET /order_pages.json
  def index   
    @order_pages = OrderPage.all.reverse
  end

  # GET /order_pages/1
  # GET /order_pages/1.json
  def show
   @order_page.user = current_user if current_user 
  

  end

  # GET /order_pages/new
  def new
  
    @order_page = OrderPage.new
  end

  # GET /order_pages/1/edit
  def edit
  end

  # POST /order_pages
  # POST /order_pages.json
  def create     
    @order_page = OrderPage.new(order_page_params)
    @order_page.user = current_user if current_user
    respond_to do |format|
      if @order_page.save
        format.html { redirect_to @order_page, notice: 'Order page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order_page }
      
      else
        format.html { render action: 'new' }
        format.json { render json: @order_page.errors, status: :unprocessable_entity }
       
      end
    end
    
  end

  # PATCH/PUT /order_pages/1
  # PATCH/PUT /order_pages/1.json
  def update
    expire_page :action => index
    respond_to do |format|
      if @order_page.update(order_page_params)
        format.html { redirect_to order_page_path, notice: 'Order page was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @order_page.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /order_pages/1
  # DELETE /order_pages/1.json
  def destroy
    @order_page.destroy
    respond_to do |format|
      format.html { redirect_to order_pages_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_page
      @order_page = OrderPage.find(params[:id])
      @order_pages = OrderPage.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_page_params
      params.require(:order_page).permit(:pickuptime_id, :order_quantity, :bread_type_id, :user_id, :comment, :vegetable_ids => [], :spread_ids => [], :sauce_ids => [])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/order_pages_helper.rb
module OrderPagesHelper
  
end

app/helpers/spreads_helper.rb
module SpreadsHelper
end

app/views/order_pages/_form.html.erb
  <%= form_for(@order_page)  do |f| %>
    <% if @order_page.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@order_page.errors.count, "error") %> prohibited this order_page from being saved:</h2>

        <ul>
          <% @order_page.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  
  
  <div class="date">
     Date <%=  Time.now.strftime('%d %b, %Y')%>
  </div>
  
  <div class="pickuptime">   
    <%= f.label :pickuptime, id: "pick" %>
    <%= f.collection_select(:pickuptime_id, Pickuptime.order("pickuptime"), :id, :pickuptime ) %>
     
  </div>
  
  <div class="quantity">
    <%= f.label :order_quantity %>
     <%= f.range_field :order_quantity, :in => 1..10, :value => 1%>      
      
     <span class="badge badge-warning"><text id="order_quantity">1</text></span>
  </div>   
  
  <div class="breadtype">   
    <%= f.label :bread_type_id, :id => "bread" %><br />
    <%= f.collection_radio_buttons(:bread_type_id, BreadType.order("name"), :id, :name)%>    
  </div>
  
  
   
  
  
  <div class="spread">
    <%= f.label :spread_id  %><br /> 
    <% Spread.all.each do |spread| %> 
        <%= check_box_tag "order_page[spread_ids][]", spread.id, f.object.spread_ids.include?(spread.id)%>
        <%= spread.name %>
    <% end %>      
  </div>
  
  <div class="vegetable">
    <%= f.label :vegetable_id  %><br /> 
    <% Vegetable.all.each do |vegetable| %> 
        <%= check_box_tag "order_page[vegetable_ids][]", vegetable.id, f.object.vegetable_ids.include?(vegetable.id)%>
        <%= vegetable.name %>
    <% end %>      
  </div>
  
  
  
  
  <div class="sauce">
    <%= f.label :sauce_id%><br /> 
    <% Sauce.all.each do |sauce| %> 
        <%= check_box_tag "order_page[sauce_ids][]", sauce.id, f.object.sauce_ids.include?(sauce.id)%>
        <%= sauce.name %>
    <% end %>      
  </div>
  
  <div class="comment">
    <%= f.label :comment, :id => "comment" %><br />
    <%= f.text_area :comment, class:'wysihtml5', id:'some-textarea', hint:"Write Your Comment Here" %>
  </div> 
   
    <div class="actions">
      <%= f.submit 'Next', :class => "btnform"%>
    </div> 
     
<% end %>

app/views/order_pages/_order_and_promo.html.erb
<div class="span4">
      <div class="row-fluid">       
          <div class="container-fluid ">
            
              <h3>Most Order</h3>
              <div class="well most_order table">
                <p><i class="icon-ok"></i> Bread     : White</p>
                <p><i class="icon-ok"></i> Spread    : Crab</p>
                <p><i class="icon-ok"></i> Vegetable : Salad, Cucumber, Tomatoe</p>
                <p><i class="icon-ok"></i> Sauce     : Moutarde</p>
              </div>
              
           
          </div>          
      </div>
      <div class="row-fluid">       
          <div class="container-fluid">       
             
              <div id="myCarousel" class="carousel slide">  
                <!-- Carousel items -->  
                <div class="carousel-inner">  
                  <div class="active item"><img src="http://www.skadate.com/blog/wp-content/uploads/2011/11/Current-Specials.gif" ></img></div>  
                  <div class="item"><img src="http://www.skadate.com/blog/wp-content/uploads/2011/11/Current-Specials.gif"  ></img></div>  
                  <div class="item"><img src="http://www.skadate.com/blog/wp-content/uploads/2011/11/Current-Specials.gif" </img></div>  
                 </div>  
                <!-- Carousel nav -->  
                <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>  
                <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>  
              </div>               
             
      </div>     
    </div>

app/views/order_pages/_price_list.html.erb
<div class="span4 ">
      <div class="container-fluid">
        <h3>Price List</h3>
        <table class="table tabel-bordered well ">
          <thead>
            <tr>
              <th>Spread</th>
              <th>Price(Eur)</th>
            </tr>
          </thead>
          <tbody>        
      
            <tr>
              <td>Crab</td>
              <td>€1.5</td>
            </tr>
        
            <tr>
              <td>Scampi</td>
              <td>€1.5</td>
            </tr>
        
            <tr>
              <td>Meatballs</td>
              <td>€1.5</td>
            </tr>
        
            <tr>
              <td>All</td>
              <td>€1.0 </td>
            </tr>    
          </tbody>
        </table>
      </div>    
    </div>

app/views/order_pages/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render :partial => 'price_list' %>
    <div class="span4">
      <h3>Edit Order</h3>
      <div class="well"><%= render 'form' %></div>
      <%= link_to '<button>Back</button>'.html_safe, order_list_path %>    
    </div>
    <%= render :partial => 'order_and_promo' %>
  </div>  
</div>

app/views/order_pages/index.html.erb
<div class="container-fluid">
  <h3>Order List</h3>

  <table class="table">
    <thead>
      <tr>
        <th>No</th>
        <th>User</th>
        <th>Date</th>
        <th>Pick up time</th>
        <th>Order quantity</th>
        <th>Bread type</th>
        <th>Sandwiches type</th>
        <th>Spreads</th>      
        <th>Vegetables</th>
        <th>Sauce</th>
        <th>Cost</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% i = 0 %>
      <% @order_pages.each_with_index do |order_page, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= order_page.user.email if order_page.user %></td>
          <td><%= order_page.created_at.strftime('%d %b, %Y') %></td>
          <td><%#= order_page.pickuptime.pickuptime %></td>
          <td><%= order_page.order_quantity %></td>
          <td><%#= order_page.bread_type.name%></td>
          <td><%#= order_page.sandwiches_type == true ? "Standard" : "Own"  %></td>
          <td><%= order_page.spreads.map(&:name).to_sentence %></td>
          <td><%#= order_page.vegetable.name %></td>
          <td><%#= order_page.sauce.name %></td>
          <td>Cost</td>
          <td><%= link_to 'Show', order_page %></td>
          <td><%= link_to 'Edit', edit_order_page_path(order_page) %></td>
          <td><%= link_to 'Delete', order_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Order page', new_order_page_path %>
  
</div>

app/views/order_pages/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render :partial => 'price_list' %>  
    <div class="span4">
      <h3>Create Your Order</h3>
      <div class="well_order"><%= render 'form' %></div>      
      <%#= link_to 'Back', root_url %>
    </div>
    <%= render :partial => 'order_and_promo' %>
  </div>
</div>

app/views/order_pages/secret.html.erb
<h3>Order List</h3>

<table class="table">
  <thead>
    <tr>
      <th>No</th>
  
      <th>Date</th>
      <th>Pick up time</th>
      <th>Order quantity</th>
      <th>Bread type</th>
      <th>Sandwiches type</th>
      <th>Spreads</th>      
      <th>Vegetables</th>
      <th>Sauce</th>
      <th>Cost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_pages.each_with_index do |order_page, i| %>
      <tr>
        <td><%= i+1 %></td>
        
        <td><%= order_page.created_at.strftime('%d %b, %Y') %></td>
        <td><%#= order_page.pickuptime.pickuptime %></td>
        <td><%= order_page.order_quantity %></td>
        <td><%= order_page.bread_type.name%></td>
        <td><%#= order_page.sandwiches_type == true ? "Standard" : "Own"  %></td>
        <td><%#= order_page.spread.name %></td>
        <td><%#= order_page.vegetable.name %></td>
        <td><%#= order_page.sauce.name %></td>
        <td>Cost</td>
        <td><%= link_to 'Show', order_page %></td>
        <td><%= link_to 'Edit', edit_order_page_path(order_page) %></td>
        <td><%= link_to 'Delete', order_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order page', new_order_page_path %>

app/views/order_pages/show.html.erb
<div class="container-fluid">
  <div class="span12">
    <p id="notice"><%= notice %></p>
      <h3>Summary Order</h3>

      <p><strong>Date: </strong><%=  Time.now.strftime(' %B %d, %Y')%></p>
  
      <p><strong>User: </strong> <%= @order_page.user.email if @order_page.user  %></p>  
  
      <p><strong>Order quantity: </strong><%= @order_page.order_quantity %></p>

      <p><strong>Bread type:</strong>  <%= @order_page.bread_type.name %></p>
  
      <p><strong>Sandwiches type: </strong><%= @order_page.sandwich_type == false ? "Standar" : "Own" %></p>

      <p><strong>Spread: </strong><%= @order_page.spreads.map(&:name).to_sentence %></p>
  
      <p><strong>Vegetable: </strong><%= @order_page.vegetables.map(&:name).to_sentence %></p>
  
      <p><strong>Sauce: </strong><%= @order_page.sauces.map(&:name).to_sentence %></p> 

      <p><strong>Pick up time:</strong><%= @order_page.pickuptime.pickuptime %></p>
  
      <%# total_unit_order= @order_page.bread_type.price + 
                                    @order_page.spread.price     +
                                    @order_page.vegetable.price  +
                                    @order_page.sauce.price       %>
                                    <%#cost = @order_page.order_quantity*total_unit_order %>
  
      <p><strong>Cost </strong>€<%= @order_page.spreads.map(&:price).to_sentence %></p>
      <p><strong>Comment </strong><%= @order_page.comment %></p>
  
    <%= link_to '<button>Edit</button>'.html_safe, edit_order_page_path(@order_page) %> 
    <%=link_to '<button>Confirm</button> '.html_safe, home_index_path%>
  </div>  
</div>